# config-management.yaml

apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: cymbal-test
  git:
    syncRepo: https://github.com/askmeegs/cymbalbank-configsync
    syncBranch: main
    secretType: none
    policyDir: "/"