# root-sync.yaml
apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    repo: https://github.com/askmeegs/cymbalbank-configsync
    revision: HEAD
    branch: main
    dir: "/"
    auth: none
    secretRef:
      name: git-creds