apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fake-editor
  namespace: psp-example
  annotations:
    configsync.gke.io/cluster-name-selector: cymbal-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: fake-user
  namespace: psp-example
